# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: defensa

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
#plugins:
#  # Automatically fetch Medium follower count
#  - MediumFollowersCountPlugin:
#      username: zhgchgli
#  # Automatically fetch Github repo star count
#  - GithubRepoStarsCountPlugin:
#      - ZhgChgLi/ZMarkupParser
#      - ZhgChgLi/ZReviewTender
#      - ZhgChgLi/ZMediumToMarkdown
#      - ZhgChgLi/linkyee

# Google Analytics tracking id
#google_analytics_id:

# HTML Title
title: "Richmond Defensa"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@richmonddefensa"

# Tagline section text
tagline: >-
    Richmond Defensa is a community defense network 

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-square-whatsapp"
      text: "Receive Alerts on Whatsapp / Recibe Alertas en WhatsApp"
      url: "https://chat.whatsapp.com/J2JcvDaEDJ22ixOQOjUN3o"
      alt: "Whatsapp"
      title: "Whatsapp"
      target: "_blank"
  - link:
      icon: "fa-brands fa-telegram"
      text: "Receive Alerts on Telegram / Recibe Alertas en Telegram"
      url: "https://t.me/rvadefensa"
      alt: "Telegram"
      title: "Telegram"
      target: "_blank"
  - link:
      icon: "fa-solid fa-palette"
      text: "Sign The Artists Against Deportation Statement / Firma La Declaración De Artistas Contra La Deportación"
      url: "https://RVADefensa.com/RAAD"
      alt: "RAAD Statement"
      title: "RAAD Statement"
      target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/richmonddefensa/"
      title: "Instagram"
      alt: "Richmond Defensa's Instagram"
      target: "_blank"
  - social:
      icon: "fa-brands fa-square-whatsapp"
      url: "https://chat.whatsapp.com/J2JcvDaEDJ22ixOQOjUN3o/"
      title: "Whatsapp"
      alt: "Receive Alerts on Whatsapp / Recibe Alertas en WhatsApp"
      target: "_blank"
  - social:
      icon: "fa-brands fa-telegram"
      url: "https://t.me/rvadefensa/"
      title: "Receive Alerts on Telegram / Recibe Alertas en Telegram"
      alt: "Receive Alerts on Telegram / Recibe Alertas en Telegram"
      target: "_blank"

# Footer text
#footer: >
#    Hi there! Follow me on Medium or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
